baseurl = "https://dvcarrillo.ninja"
title = "David Vargas Carrillo"
theme = "coder"
languagecode = "en"
defaultcontentlanguage = "en"
enableRobotsTXT = true

paginate = 20
canonifyurls = true

pygmentsstyle = "bw"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

disqusShortname = "dvcarrillo"

[params]
    author = "David Vargas Carrillo"
    avatarurl = "images/avatar.jpg"

    favicon_32 = "/img/favicon-32x32.png"
    favicon_16 = "/img/favicon-16x16.png"

    hidecredits = true
    hidecopyright = false

    rtl = false

    math = true
    custom_css = []

# Social links
[[params.social]]
    name = "Github"
    icon = "fab fa-github-square fa-2x"
    weight = 1
    url = "https://github.com/dvcarrillo/"
[[params.social]]
    name = "LinkedIn"
    icon = "fab fa-linkedin fa-2x"
    weight = 2
    url = "https://www.linkedin.com/in/dvcarrillo/"
[[params.social]]
    name = "Flickr"
    icon = "fab fa-flickr fa-2x"
    weight = 3
    url = "https://www.flickr.com/photos/davidvargas996/"
# [[params.social]]
#     name = "Twitter"
#     icon = "fab fa-twitter-square fa-2x"
#     weight = 4
#     url = "https://twitter.com/.../"
[[params.social]]
    name = "Contact"
    icon = "fas fa-envelope-square"
    weight = 5
    url = "mailto:hello@dvcarrillo.ninja"

# Multilingual mode
[languages]
    [languages.en]
        languagename = "English"
        footercontent = "My website is still under heavy development. Stay tuned!"

        [languages.en.params]
            info = "Software Engineer"
            description = "David Vargas Carrillo's personal website and blog. I speak about software and technology."
            keywords = "blog,developer,personal,coder,software,technology"

        [languages.en.menu] 

            [[languages.en.menu.main]]
            name = "About"
            weight = 1.0
            url = "/about/"

            # [[languages.en.menu.main]]
            # name = "Blog"
            # weight = 2.0
            # url = "/posts/"

            # [[languages.en.menu.main]]
            # name = "Projects"
            # weight = 3.0
            # url = "/projects/"

            [[languages.en.menu.main]]
            name = "Contact me"
            weight = 4.0
            url = "/contact/"

    [languages.es]
        languagename = "Español"
        footercontent = "Mi sitio aún está en pleno desarrollo. ¡Vuelva pronto para más!"

        [languages.es.params]
            info = "Ingeniero de Software"
            description = "Sitio web personal y blog de David Vargas Carrillo. Hablo sobre software y tecnología."
            keywords = "blog,desarrollo,personal,programación,software,tecnologia"

        [languages.es.menu]

            [[languages.es.menu.main]]
            name = "Sobre mí"
            weight = 1.0
            url = "/es/about/"

            # [[languages.es.menu.main]]
            # name = "Blog"
            # weight = 2.0
            # url = "es/posts/"

            # [[languages.es.menu.main]]
            # name = "Proyectos"
            # weight = 3.0
            # url = "/es/projects/"

            [[languages.es.menu.main]]
            name = "Contacto"
            weight = 4.0
            url = "/es/contact/"
